############################################################ 
# Test Case: ABB-RCV-Mobile Inbound Receiving.feature
# 
# Functional Area: Receiving
# Author: Netlogistik
# Blue Yonder WMS Version: Consult Bundle Release Notes
# Test Case Type: Regression
# Blue Yonder Interfaces Interacted With: Mobile, MOCA
# 
# Description:
# This Test Case generates a receipt via MSQL and receives it in the Mobile App.
#
# Input Source: Test Case Inputs/ABB-RCV-4010.csv
# Required Inputs:
# 	trlr_num - This will be used as the trailer number when receiving by Trailer. If not, this will be the Receive Truck and Invoice Number
#	inv_num - This will be used as the Invoice Number when receiving by Trailer. If receiving by PO - this will not be used.
#	yard_loc - If receiving by Trailer, this is where your Trailer needs to be checked in. Must be a valid and open dock door.
#	invtyp - This need to be a valid Invoice Type, that is assigned in your system
#	prtnum - This needs to be a valid part number that is assigned in your system. Will use the default client_id.
#	rcvsts - Receiving status created on the Invoice Line being loaded
#	expqty - The number expected
# 	supnum - A valid supplier
#	rcv_qty - quantity to receive for Mobile App input
#	putaway_method - 1 is Directed, 2 is Sorted, 3 is Undirected.
#	asn_flg - Flag for ASN Receipts
#	actcod - Activity Code
#	lpn - use explicit LPN for load instead of one generated by system
# Optional Inputs: 
#	rcv_prtnum - Populate this field to test blind receiving 
#	validate_loc - Location to be validated for Directed Putaway, when doing Directed Putaway only
#	lotnum - Lotnum to add to the receiving line when creating the invoice and to be used for receiving if the item is lot tracked
#	rec_loc - A valid Receiving Staging lane when using sorting putaway
#	dep_loc - A valid Receiving Staging lane for deposit for undirected putaway
#	ap_sts - Valid Aging profile status, if the part has an aging profile
#	qa_sts - Valid QA Status, if the part should be received in a QA Status
#	expect_discrepancies - on receiving completion should process expect discrepancies
#	revlvl - Revision Level
#
# Assumptions:
# - Regression runs require parts and enough config to deposit inventory into the receive stage location
# - Processing will handle standard LPN flow for blind receipts, over receipts, multi-client, multi-wh, lot tracking, aging, qa directed
# - Putaway Method defaults to Undirected If I verify variable is not specified in Feature or CSV
# - Processing ends with the deposit into the dep_loc
#
# Notes:
# - Test Case Inputs (CSV) - Examples:
#	Example Row: OUTCAP_ONLY serialization prtnum being received (should not require serial number inputs)
#	Example Row: CRDL_TO_GRAVE serialization with receive quantity of 1
#	Example Row: CRDL_TO_GRAVE serialization with receive quantity of 20
# 	Example Row: putaway_method - 1 for Directed, using the dep_loc input for deposit
#	Example Row: putaway_method - 2 for Sorted, using the rec_loc input for deposit
#	Example Row: putaway_method - 3 for Undirected, using the dep_loc input for deposit
#	Example Row: No serialization, receiving Subload tracked part
#	Example Row: No serialization, receiving Detail tracked part
#	Example Row: No serialization, receiving Lot Enable, Revision Level tracked part
#
############################################################
Feature: ABB-RCV-03 Receive Inbound Shipment NP6
 
Background:
############################################################
# Description: Imports dependencies, sets up the environment.
#############################################################
 
Given I "setup the environment"
    Then I assign all chevron variables to unassigned dollar variables
    And I import scenarios from "Utilities/Base/Environment.feature"
    When I execute scenario "Set Up Environment"
 
    Given I execute scenario "Mobile Receiving Imports"
 
    Then I assign "ABB-RCV-03" to variable "test_case"
    When I execute scenario "Test Data Triggers"
 
 
After Scenario:
#############################################################
# Description: Logs out of the interface and cleans up the dataset
#############################################################
 
Given I "perform test completion activities including logging out of the interfaces"
    Then I execute scenario "Test Completion"
 
@ABB-RCV-03 NP5
Scenario Outline: ABB-RCV-03 Receive Inbound Shipment
CSV Examples: Test Case Inputs/ABB INPUTS NP6/ABB-RCV-03.csv
 
Given I "execute pre-test scenario actions (including pre-validations)"
    And I execute scenario "Begin Pre-Test Activities"
 
Then I "login to the Mobile App"
    When I execute scenario "Mobile Login"
 
When I "open the Receipt, process workflow, receive each receipt line individually, and deposit to location"
    Given I "open the Receipt"
        Then I execute scenario "Mobile LPN Receiving Menu"
        And I execute scenario "Mobile Enter Receive ID"
       
        Then I execute scenario "Mobile Process Workflow"
    Then I execute scenario "Mobile Receiving"
 
            Then i wait $wait_short seconds
            Then I "execute post-test scenario actions (including post-validations)"
        And I execute scenario "End Post-Test Activities"
       
Then I echo "Completed "