###########################################################
# Copyright 2024, Netlogistik.
# All rights reserved.  Proprietary and confidential.
#
# This file is subject to the license terms found at
# https://www.cycleautomation.com/end-user-license-agreement/
#
# The methods and techniques described herein are considered
# confidential and/or trade secrets.
# No part of this file may be copied, modified, propagated,
# or distributed except as authorized by the license.
##########################.##################################
# Test Case: rcv-all_1.feature
#
# Functional Area: Receiving
# Author: Netlogistik
# Blue Yonder WMS Version: Consult Bundle Release Notes
# Test Case Type: Regression
# Blue Yonder Interfaces Interacted With: Web, MOCA
#
# Description: It's doing the general receipt process.
#	Review Inbound Shipment, Check In Inbound Shipment, Web Full Create Footprint
#
# Input Source: Test Case Inputs\ABB_Click_N_Win\Inbound\rcv_all.csv
#
# Required Inputs Per Scenario:
#	Scenario "Review Inbound Shipment": trlr_num,trknum
#	Scenario "Check In Inbound Shipment": trlr_num,yard_loc,seal
#	Scenario "Mobile Receive Inbund Shipment": trlr_num,inv_num,invtyp,trknum,dep_loc,supnum,putaway_method,rcvsts,prtnum,expqty,rec_loc,rcv_uom,rcv_qty,asn_flg,validate_loc,actcod,rcv_prtnum,lpn,expect_discrepancies,yard_loc
#	Scenario "Inbound Complete OSD Receipt": trlr_num,yard_loc,generate_screenshot
#	Scenario "Inbound Close And Dispatch": wave_num,trlr_num,yard_loc
#	Scenario "Store Received Inventory": dep_loc,userlogin
#	Scenario "Mobile Store Pallet Directed": userlogin,vehtyp,trknum,dep_loc_id,mobile_start_loc,empty,lpn,dep_loc
#
# Inputs:
#	trlr_num - this will be the Receive Truck
#	trknum - The truck number of the inbound shipment
#	yard_loc - If receiving by Trailer, this is where your Trailer needs to be checked in. Must be a valid and open dock door.
#	seal - This will be used as Transport Equipment Seal
#	inv_num - This will be used as the Invoice Number when receiving by Trailer. If receiving by PO - this will not be used.
#	invtyp - This need to be a valid Invoice Type, that is assigned in your system
#	dep_loc - A valid Receiving Staging lane for deposit for undirected putaway
# 	supnum - A valid supplier
#	putaway_method - 1 is Directed, 2 is Sorted, 3 is Undirected.
#	rcvsts - Receiving status created on the Invoice Line being loaded
#	prtnum - This needs to be a valid part number that is assigned in your system. Will use the default client_id.
#	expqty - The number expected
#	rec_loc - A valid Receiving Staging lane when using sorting putaway
#	rcv_uom - receieve unit of measure
#	rcv_qty - quantity to receive for Mobile App input
#	asn_flg - Flag for ASN Receipts
#	validate_loc - Location to be validated for Directed Putaway, when doing Directed Putaway only
#	actcod - Activity Code
#	rcv_prtnum - Populate this field to test blind receiving
#	lpn - use explicit LPN for load instead of one generated by system
#	expect_discrepancies - on receiving completion should process expect discrepancies
#	wrong_dep_loc - incorrect deposit location
#	generate_screenshot - generate screenshot of inventory display screen
#	wave_num - Wave number to be created
#	userlogin - user name who's going to be assigned the work
#   vehtyp - Vehicle type
#	dep_loc_id - id location to start with mobile
#	mobile_start_loc - this is the code for Mobile Start Location
#	client_id - This will be used as the client_id for the outbound order
# 	oprcod - This will be used to validate the type of operation performed
#	wrong_location - boolean which specifies if test needs to test wrong location
#	overreceiving -> If you are going to receive more than expected, fill this
#	unexpected_item -> if you are going to receive an item that was not expected, fill this
#	movb4osd -> if you want to move inventory before osd put YES in the field
#	override - if set to TRUE, will override the deposit location
#	over_code - the override code to be input
#	override_f2 - use F2 to show overrtide code
#	qa_sts - Valid QA Status, if the part should be received in a QA Status
#	ftprnt_cols - use to separate information, must leave in blank
#	item_name - item were you want to create a footprint
#	ft_name - footprint name
#	ft_desc - footprint description
#	ftunit_measure - Can be Each, Case and Pallet
#	ftunit_qty - assign quantity for the measures
#	ft_length - assign lenght for the measures
#	ft_width - assign width for the measures
#	ft_height - assign height for the measures
#	ftgross_weigth - assign gross_weigth for the measures
#	ftnet_weigth - assign ftnet_weigth for the measures
#
# Optional Inputs:
# 	None
#
# Assumptions:
# None
#
# Notes:
# None
#
############################################################
Feature: rcv-all

Background:
	############################################################
	# Description: Imports dependencies, sets up the environment.
	#############################################################

	Given I "setup the environment"
	Then I assign all chevron variables to unassigned dollar variables
	And I import scenarios from "Utilities/Base/Environment.feature"
	When I execute scenario "Set Up Environment"

	Given I execute scenario "Web Receiving Imports"
	Given I execute scenario "Mobile Receiving Imports"
	Given I execute scenario "Wave Imports"
	And I execute scenario "Outbound Planner Imports"
	And I execute scenario "Inventory Adjust Imports"
	Then I execute scenario "Web Environment Setup"
	And I import scenarios from "Utilities\Custom\Web\Inbound Performance.feature"

	Then I assign "ABB-RCV-01" to variable "test_case"
	When I execute scenario "Test Data Triggers"
	Then I execute MOCA script "Scripts\MSQL_Files\Custom\generate_lpn.msql"
	And I verify MOCA status is 0
	Then I assign row 0 column "lodnum" to variable "lpn"
	And I assign "TRUE" to variable "check_in"
	Then I assign "" to variable "overreceiving"
	And I assign "RCV" to variable "trlr_cod"
	Then I assign "YES" to variable "is_batch"

	#And I "load the dataset"
	#	Then I assign "receiving" to variable "dataset_directory"
	#	And I execute scenario "Perform MOCA Dataset"

	After Scenario:
	#############################################################
	# Description: Logs out of the interface and cleans up the dataset
	#############################################################

	#When I execute MOCA script "Scripts\MSQL_Files\Custom\delete_cyclelock_dock_data.msql"

	Given I "perform test completion activities including logging out of the interfaces"
	Then I execute scenario "Test Completion"

#And I "cleanup the dataset"
#	Then I assign "receiving" to variable "cleanup_directory"
#	And I execute scenario "Perform MOCA Cleanup Script"

@ABB-RCV-01
Scenario: rcv-all 1

Given I "execute pre-test scenario actions (including pre-validations)"
And I execute scenario "Begin Pre-Test Activities"
Then I "log into the Web Browser and review shipment, then check in and create footprint if it applies"
Then I execute scenario "Web Login"

  Then I assign $trknum to variable "trlr_num"
  And I execute scenario "Review Inbound Shipment"
  Then I execute scenario "Check In Inbound Shipment"
  And I execute scenario "Web Full Create Footprint"

 Given I "close the web browser"
 Then I execute scenario "Close Web Browser"

Given I "receive in mobile"
And I execute scenario "Mobile Receive Inbound Shipment"

Then I "execute post-test scenario actions (including post-validations)"
And I execute scenario "End Post-Test Activities"